version: '3.8'

services:

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  trino:
    image: trinodb/trino
    container_name: trino
    ports:
      - "8081:8080"
    volumes:
      - ./trino/etc:/etc/trino
      - ./trino/data:/data/trino  # <-- Agrega esta línea

  airflow:
    image: apache/airflow:2.8.1
    container_name: airflow
    depends_on:
      - minio
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: bash -c "airflow db init && airflow users create \
      --username admin --password admin \
      --firstname Admin --lastname User \
      --role Admin --email admin@example.com && \
      airflow webserver"

  app:
    build: .
    container_name: app
    volumes:
      - ./scripts:/app/scripts
      - ./data:/app/data
    working_dir: /app
    command: sleep infinity
    depends_on:
      - minio

volumes:
  minio_data:
